version: '3.4'

services:
  sql.data:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"    # Important: In a production environment your should remove the external port

  ecommerce.data:
    ports:
      - "6379:6379"    # Important: In a production environment your should remove the external port

  rabbitmq:
    ports:
      - "15672:15672"  # Important: In a production environment your should remove the external port
      - "5672:5672"    # Important: In a production environment your should remove the external port

  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityUrl=http://10.0.75.1:5105
      - RedisConnectionString=ecommerce.data:6379
      - RabbitMQConnectionString=amqp://rabbitmq
    ports:
      - "5103:80"

  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80

    ports:
      - "50518:80"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - CallBackUrl=http://localhost:5100/
      - RabbitMQConnectionString=amqp://rabbitmq
    ports:
      - "5105:80"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  ordering.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionString=${CASADOCODIGO_ORDERING_DB:-Server=sql.data;Database=Ordering;User Id=sa;Password=Pass@word;}
      - SignalRServerUrl=http://mvc/
      - RabbitMQConnectionString=amqp://rabbitmq
    ports:
      - "5106:80"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  mvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CatalogUrl=http://catalog.api/
      - IdentityUrl=http://10.0.75.1:5105/
      - BasketUrl=http://basket.api/
      - OrderingUrl=http://ordering.api/
      - CallBackUrl=http://localhost:5100/
      - SignalRServerUrl=http://mvc/
      - RedisConnectionString=ecommerce.data:6379
    ports:
      - "5100:80"

  webstatus:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - BasketHC=http://basket.api/hc
      - MvcHC=http://mvc/hc
      - CatalogHC=http://catalog.api/hc
      - IdentityHC=http://10.0.75.1:5105/hc
      - OrderingHC=http://ordering.api/hc
    ports:
      - "5107:80"

