version: '3.4'

services:
  elasticsearch:
    image: nshou/elasticsearch-kibana

  sql.data:
    image: microsoft/mssql-server-linux:2017-latest

  ecommerce.data:
    image: redis:alpine

  rabbitmq:
    hostname: rabbit
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  basket.api:
    image: basketapi
    build:
      context: .
      dockerfile: Services/Basket.API/Dockerfile
    depends_on:
      - rabbitmq

  catalog.api:
    image: catalogapi
    build:
      context: .
      dockerfile: Services/Catalog.API/Dockerfile
    depends_on:
      - rabbitmq

  identity.api:
    image: identityapi
    build:
      context: .
      dockerfile: Services/Identity.API/Dockerfile
    depends_on:
      - rabbitmq

  ordering.api:
    image: orderingapi
    build:
      context: .
      dockerfile: Services/Ordering.API/Dockerfile
    depends_on:
      - rabbitmq
      - sql.data

  mvc:
    image: mvc
    build:
      context: .
      dockerfile: Web Apps/MVC/Dockerfile
    depends_on:
      - ecommerce.data
      - rabbitmq

  webstatus:
    image: webstatus
    build:
      context: .
      dockerfile: Web Apps/WebStatus/Dockerfile
