version: '3.4'

services:
  rabbitmq:
    ports:
      - "15672:15672"  # Important: In a production environment your should remove the external port
      - "5672:5672"    # Important: In a production environment your should remove the external port

  elasticsearch:
    ports:
      - "9200:9200"
      - "9300:9300"
      - "5601:5601"
      - "12201:12201/udp"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"

  webstatus:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - HealthChecks-UI__HealthChecks__1__Name=Basket HTTP Check
      - HealthChecks-UI__HealthChecks__1__Uri=http://basket.api/hc
      - HealthChecks-UI__HealthChecks__2__Name=Catalog HTTP Check
      - HealthChecks-UI__HealthChecks__2__Uri=http://catalog.api/hc
      - HealthChecks-UI__HealthChecks__3__Name=MVC HTTP Check
      - HealthChecks-UI__HealthChecks__3__Uri=http://mvc/hc
      - HealthChecks-UI__HealthChecks__4__Name=Identity HTTP Check
      - HealthChecks-UI__HealthChecks__4__Uri=http://10.0.75.1:5105/hc
      - HealthChecks-UI__HealthChecks__5__Name=Ordering HTTP Check
      - HealthChecks-UI__HealthChecks__5__Uri=http://ordering.api/hc
    ports:
      - "5107:80"

  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ELASTICSEARCH_URL=http://10.0.75.1:9200
    ports:
      - "5108:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
